apiVersion: garden.io/v1
kind: Project
name: repro
defaultEnvironment: development

environments:
  - name: development
  - name: production

providers:
  - name: exec
    environments: [ development, production ]
  - name: terraform
    environments: [ development, production ]

---
kind: Run
name: run-task
type: exec
environments:
  - production
  - development
#dependencies:
  #$if: ${environment.name == 'production'}
  #$then:
    #- deploy.tf-production
spec:
  $if: ${environment.name != 'production'}
  $then:
    command: ["sh", "-c", "echo 'Hello from garden-remote in development'"]
  $else:
    command: ["sh", "-c", "echo '${runtime.services.tf-production.outputs.welcome_message}'"]

---
kind: Deploy
type: terraform
name: tf-production
environments:
  - production
spec:
  root: .